url: https://tff-burbach.github.io
baseurl: 

# Site settings
title: TFF Burbach
email: ralph.kiefer@web.de
description: "TFF Burbach; Saarbruecken; Tischfussball; Sport; Sportmannschaft; STFV"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/TischFussballFreundeBurbach/

# Postal address (add as many lines as necessary)
address:
  - line: In den Hanfgärten 4
  - line: 66115 Saarbrücken-Burbach
  - line: 0681-77773

# Build settings
markdown: kramdown
permalink: pretty

# # Saas
# sass:
#     sass_dir: _sass
#     style: compact # possible values: nested expanded compact compressed    